GameTracker/config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#home' 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new' 
  post '/signup' => 'users#create' 
  delete '/logout' => 'sessions#destroy'
  get '/most_popular' => 'games#most_popular' 

  get '/auth/:provider/callback' => 'sessions#create'
 
  resources :categories   
  resources :reviews
  # nested route for review under games
  resources :games do
    resources :reviews, only: [:new, :index]
  end
  
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

GameTracker/app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(object.errors.count, "error") %> prohibited this from being saved:</h2>

    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

GameTracker/app/views/layouts/_loggedin_links.html.erb
<%= button_to "Log Out", logout_path, method: :delete %> |
<%= link_to "Add a Game", new_game_path %> |
<%= link_to "All Games", games_path %> |
<%= link_to "Add a Review", new_review_path %> |
<%= link_to "All Reviews", reviews_path %> |
<%= link_to "All Categories", categories_path %> |
<%= link_to "Home", user_path(:user_id)%> 

GameTracker/app/views/layouts/_loggedout_links.html.erb
<%= link_to "Login", login_path %> |
<%= link_to "Signup", signup_path %> |
<%= link_to "Sign in with Google", "/auth/google_oauth2" %> 

GameTracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GameTracker</title>
    <%= csrf_meta_tags %>    
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    
  </head>


    <body>
    <div><%= render_nav_bar %></div>
      <%= yield %>
    </body>
</html>