GameTracker/config/routes.rb
Rails.application.routes.draw do

  get '/' => 'sessions#home' 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new' 
  post '/signup' => 'users#create' 
  delete '/logout' => 'sessions#destroy'
  get '/most_popular' => 'games#most_popular' 

  get '/auth/:provider/callback' => 'sessions#create'
 
  resources :categories   
  resources :reviews
  # nested route for review under games
  resources :games do
    resources :reviews, only: [:new, :index]
  end
  
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

GameTracker/app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :reviews
  has_many :users, through: :reviews
  
  validates :name, presence: true, uniqueness: true
  validates :release_date, presence: true  
  validate :not_a_duplicate 

  scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')} # scope method, ordering reviews by rating given
  scope :most_popular, -> {left_joins(:reviews).group(:id).order('count(reviews.id) desc').limit(3)} # scope method, ordering review by amount

  def self.alpha # order by alphabets 
    order(:name) 
  end
  # attributes for category
  def category_attributes=(attributes)
    self.category = Category.find_or_create_by(attributes) if !attributes['name'].empty?
    self.category 
  end

  def not_a_duplicate
    # if there is already a game with this name and release date
    game = Game.find_by(name: name, release_date: release_date) 
    if !!game && game != self
      errors.add(:name, 'has already been added for that release date')
    end
  end 
  
  def category_name
    category.try(:name)
  end
    
  def name_and_category
    "#{name} - #{category.try(:name)}"
  end
 
end

GameTracker/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :redirect_if_not_logged_in
  before_action :set_game, only: [:show, :edit, :update] 
  
  # make new game
  def new 
    @game = Game.new  
    @game.build_category 
  end 
  # save new game with existing category or make a new category
  def create
    @game = Game.new(game_params) 
    @game.user_id = session[:user_id] 
   
    if @game.save 
      redirect_to game_path(@game) 
    else
      @game.build_category  
      render :new 
    end
  end
  # index for cateory uses scope to sort games in each category by rating
  def index   
    if params[:category_id]
      category = Category.find(params[:category_id])
      @games = category.games 
    else 
      @games = Game.order_by_rating.includes(:category) 
    end 
  end 

  def show 
    
  end 
  # edit game function
  def edit 
    if authorized_to_edit?(@game) 
      render :edit   
    else 
      redirect_to game_path(@game)   
    end
  end 
  # update the change in the edit
  def update   
    if @game.update(game_params)
      redirect_to game_path(@game)
    else
      render :edit
    end 
  end 
  # rate game
  def most_popular 
    @games = Game.most_popular 
  end 
  
  private 
  # parameter for game
  def game_params
    params.require(:game).permit(:name, :price_range, :release_date, :category_id, category_attributes: [:name])
  end
  # find game
  def set_game
    @game = Game.find_by(id: params[:id])
    redirect_to games_path if !@game 
  end
  # redirect if not own by current user
  def redirect_if_not_authorized 
    if @game.update(name: params[:name], price_range: params[:price_range], release_date: params[:release_date])   
      redirect_to game_path(@game)
    else
      redirect_to user_path(current_user)     
    end 
  end

end

GameTracker/app/helpers/games_helper.rb
module GamesHelper
end

GameTracker/app/views/games/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @game}  %>
<%= form_for(@game) do |f|%> 
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    
    <div>
      <%= f.label :price_range %> 
      <%= f.select :price_range,options_for_select(["Lower than $20", "Between $20-$50", "Higher than $50"]), include_blank: true %>   
    </div>
    <div>
      <%= f.label :release_date %>
      <%= f.text_field :release_date %> 
    </div>

    <p> Select a Category that already exists: </p>
    <div>
      <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: 'Select One'%>
  
    </div>
  
    <p> Or create a new Category: </p>
    <div>
      <%= f.fields_for :category do |c| %>
        <%= c.label :name %>
        <%= c.text_field :name %>
      <% end %> 
    </div> 
    <br>
    <%= f.submit %>
  <% end %>

GameTracker/app/views/games/edit.html.erb
<h1>Edit your Game</h1>

<%= render partial: 'form'%>

GameTracker/app/views/games/index.html.erb
<h1>Game List</h1>
<%= form_tag('/games',:method=>:get) do %>                          
<%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name", params[:category_id]), include_blank: 'Select One' %>    
<%= submit_tag %>
<% end %>

<% @games.each do |r| %>

  <h2><%= link_to r.name, game_path(r.id)%> - <%= r.category.name %> - <%= r.price_range %> </h2>
  <%= link_to "Write a review", new_game_review_path(r.id) %> 
  <p><%= r.release_date %></p>
  <% end %>
  


GameTracker/app/views/games/most_popular.html.erb
<% @games.each do |r| %>
<%= r.name %> 
<% end %> 

GameTracker/app/views/games/new.html.erb
<h1>List a New Game:</h1> 

<%= render partial: 'form'%>

GameTracker/app/views/games/show.html.erb
<h1><%= @game.name%>  </h1>

<h2> <%= @game.category_name %> </h2>
<div>
  <p><%= @game.price_range %></p>
  <p><%= @game.release_date %></p>
</div>

<%= link_to "Edit #{@game.name}", edit_game_path(@game) if @game.user == current_user%>

<br></br>

<%= link_to "See all Reviews", game_reviews_path(@game) %>